sudo: required

services:
 - docker

before_install:
 - docker build -t nickadamu/fib-test -f ./client/Dockerfile.dev ./client

script:
 - docker run nickadamu/fib-test npm test -- --coverage

after_success:
 - docker build -t nickadamu/multi-client ./client
 - docker build -t nickadamu/multi-nginx ./nginx
 - docker build -t nickadamu/multi-server ./server
 - docker build -t nickadamu/multi-worker ./worker
#  Login into docker cli
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push images to docker hub
 - docker push nickadamu/multi-client
 - docker push nickadamu/multi-worker
 - docker push nickadamu/multi-nginx
 - docker push nickadamu/multi-server